spring.application.name=onyx

#database configuration
spring.datasource.url=jdbc:mysql://{your database url}:3306/{your database name}
spring.datasource.username={database username}
spring.datasource.password={database password}
#mySQL wait_timeout = 28800 seconds ( 28800000ms )
#hikary maxLifetime must be several seconds shorter
spring.datasource.hikari.maxLifetime=28700000 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

#disable url cookies
server.servlet.session.tracking-modes=COOKIE

#stripe
stripe.secretApiKey={your stripe secret key}
stripe.domain={https url for stripe success/cancel redirect}